# 1. Usar uma imagem base oficial do Python. A versão 'slim' é mais leve.
FROM python:3.10-slim

# 2. Definir o diretório de trabalho dentro do container
WORKDIR /app

# 3. Copiar o arquivo de dependências PRIMEIRO
# Isso aproveita o cache do Docker. As dependências só serão reinstaladas se o requirements.txt mudar.
COPY requirements.txt .

# 4. Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiar o resto do código da aplicação para o diretório de trabalho
# O primeiro '.' é a pasta do serviço no seu computador, o segundo '.' é o WORKDIR dentro do container.
COPY . .
